sudo: false
language: c
services:
  - docker
before_install:
  - docker pull $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH
script:
  - docker run -it -v "$(pwd)"/:/git $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH /bin/sh -c "cd /git; ./build.sh"
