sudo: false
language: c
services:
  - docker
before_install:
  - docker pull zgiles/nycmeshbuild-docker:$TRAVIS_BRANCH
script:
  - docker run -it -v "$(pwd)"/:/git zgiles/nycmeshbuild-docker:latest /bin/sh -c "cd /git; ./build.sh"
