version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y git make gcc g++ zlib1g-dev libssl-dev wget subversion file python apt-utils binfmt-support vim apt-file xz-utils sudo subversion zlib1g-dev gawk flex unzip bzip2 gettext build-essential libncurses5-dev libncursesw5-dev libssl-dev binutils cpp psmisc docbook-to-man gcc-multilib g++-multilib
  build:
    commands:
      - echo Build started on `date`
      - ./build.sh | tee stdout
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - images/*
    - stdout
